-- =====================================================================
-- CELPLAC GWMI · 0007 · Dados de referência (dimensões e configuração)
-- Nada aqui é dado de mercado. Mapeamentos oficiais (CO_PAIS, NCM8, URF,
-- unidades) são carregados das tabelas auxiliares do Comex Stat pelo ETL.
-- =====================================================================

INSERT INTO meta.source (source_id, name, url, source_type, periodicity, coverage, methodology, license_note, expected_lag_days, reliability) VALUES
('comexstat','Comex Stat — MDIC/SECEX','https://comexstat.mdic.gov.br','oficial','mensal','Exportações e importações brasileiras por NCM, país, UF, via e URF','Registros aduaneiros; FOB US$, kg líquido, quantidade estatística','Dados abertos',45,'ALTA'),
('bcb_ptax','Banco Central do Brasil — PTAX (Olinda OData)','https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata/','oficial','diária','Taxas de câmbio PTAX por moeda','Boletim de fechamento PTAX','Dados abertos',2,'ALTA'),
('bcb_sgs','Banco Central do Brasil — SGS','https://api.bcb.gov.br/dados/serie/','oficial','diária/mensal','Séries temporais: juros, atividade, câmbio','Séries oficiais do BCB','Dados abertos',30,'ALTA'),
('ibge_sidra','IBGE — SIDRA (PEVS, PIM-PF)','https://apisidra.ibge.gov.br','oficial','anual/mensal','Produção da silvicultura (PEVS), produção industrial (PIM-PF)','Pesquisas oficiais IBGE','Dados abertos',60,'ALTA'),
('snif','SNIF — Serviço Florestal Brasileiro','https://snif.florestal.gov.br','oficial','anual','Florestas plantadas, produção e comércio florestal','Compilação de bases oficiais e setoriais','Dados abertos',365,'MÉDIA'),
('fao','FAOSTAT — Forestry Production and Trade','https://www.fao.org/faostat','organismo_internacional','anual','Produção, comércio e consumo aparente de produtos florestais','Questionário conjunto FAO/ITTO/UNECE/Eurostat; estimativas FAO','CC BY 4.0 (verificar)',540,'MÉDIA'),
('comtrade','UN Comtrade','https://comtradeplus.un.org','organismo_internacional','mensal/anual','Comércio bilateral por código SH','Dados declarados pelos países','Requer chave de API; termos de uso',90,'MÉDIA'),
('itto','ITTO — Market Information Service','https://www.itto.int','organismo_internacional','quinzenal','Preços e notícias de madeira tropical e compensado','Cotações reportadas por correspondentes','Importação manual (CSV)',20,'MÉDIA'),
('iba','Ibá — Indústria Brasileira de Árvores','https://iba.org','setorial','anual/periódica','Florestas plantadas, painéis, pinus e eucalipto','Dados de associadas + fontes oficiais','Importação manual (CSV)',120,'MÉDIA'),
('abimci','ABIMCI','https://abimci.com.br','setorial','periódica','Compensados, lâminas, serrados','Estudos setoriais','Importação manual (CSV)',120,'MÉDIA'),
('anfir','ANFIR — Implementos Rodoviários','https://www.anfir.org.br','setorial','mensal','Emplacamentos de implementos rodoviários','Registros de emplacamento','Importação manual (CSV)',20,'ALTA'),
('fred','FRED — Federal Reserve Bank of St. Louis','https://fred.stlouisfed.org','oficial','mensal','Construção, produção industrial, juros EUA','Redistribui séries oficiais (Census, BLS, Fed)','Requer chave de API gratuita',30,'ALTA'),
('eurostat','Eurostat','https://ec.europa.eu/eurostat','oficial','mensal','Comércio (Comext) e construção na UE','Estatísticas harmonizadas','Dados abertos',60,'ALTA'),
('nbs','National Bureau of Statistics of China','https://www.stats.gov.cn','oficial','mensal','Atividade, construção, produção industrial','Estatísticas oficiais','Importação manual (CSV)',30,'MÉDIA'),
('inegi','INEGI — México','https://www.inegi.org.mx','oficial','mensal','Construção, atividade, comércio','Estatísticas oficiais','Dados abertos',45,'ALTA'),
('worldbank','World Bank — Open Data','https://data.worldbank.org','organismo_internacional','anual','Macro global, população','Compilação de fontes nacionais','CC BY 4.0',365,'ALTA'),
('imf','IMF Data','https://www.imf.org/en/Data','organismo_internacional','trimestral','PIB, inflação, projeções','Estatísticas e projeções do FMI','Dados abertos',90,'ALTA'),
('eia','U.S. EIA — Petroleum Prices','https://www.eia.gov','oficial','diária','Brent, WTI, combustíveis','Cotações spot','Dados abertos (API key)',7,'ALTA'),
('drewry','Drewry World Container Index','https://www.drewry.co.uk','especializada','semanal','Frete spot de contêiner em rotas principais','Cotações de mercado spot','Licença a verificar — importação manual',7,'MÉDIA'),
('fbx','Freightos Baltic Index (FBX)','https://fbx.freightos.com','especializada','diária/semanal','Frete de contêiner por rota','Índice de preços spot','Licença a verificar — importação manual',7,'MÉDIA'),
('antaq','ANTAQ — Estatístico Aquaviário','https://www.gov.br/antaq','oficial','mensal','Movimentação nos portos brasileiros','Declarações de terminais','Dados abertos',60,'ALTA'),
('news','Feeds jornalísticos licenciados (a definir)',NULL,'jornalistica','contínua','Notícias de mercado, comércio, logística e geopolítica','Curadoria + News Impact Engine','Licenciamento a definir',1,'BAIXA'),
('celplac_erp','ERP CELPLAC (Fase 5)',NULL,'interna','diária','Vendas, exportações, clientes, produtos, preços, margem, estoque','Integração via API/ETL','Interno',1,'ALTA'),
('gwmi_calc','GWMI — indicador calculado',NULL,'interna','mensal','Indicadores derivados de fatos do DW (fórmula registrada em dim_indicator)','Cálculo determinístico sobre dados de origem rastreáveis','Interno',0,'ALTA'),
('demo','DEMO — gerador de dados simulados',NULL,'simulada','—','Dados fictícios para desenvolvimento e demonstração','Gerador determinístico (seed fixa)','NUNCA apresentar como real',0,NULL);

INSERT INTO dw.dim_country (iso3, iso2, m49, name_pt, name_en, region, subregion, is_mercosur, is_eu, is_aggregate, lat, lon) VALUES
('WLD',NULL,0,'Mundo','World','Agregado',NULL,false,false,true,NULL,NULL),
('EUU','EU',97,'União Europeia','European Union','Europa','UE',false,false,true,50.0,10.0),
('XXX',NULL,NULL,'Não identificado','Unidentified','Agregado',NULL,false,false,true,NULL,NULL),
('BRA','BR',76,'Brasil','Brazil','América do Sul',NULL,true,false,false,-14.2,-51.9),
('ARG','AR',32,'Argentina','Argentina','América do Sul',NULL,true,false,false,-34.0,-64.0),
('PRY','PY',600,'Paraguai','Paraguay','América do Sul',NULL,true,false,false,-23.4,-58.4),
('URY','UY',858,'Uruguai','Uruguay','América do Sul',NULL,true,false,false,-32.5,-55.8),
('BOL','BO',68,'Bolívia','Bolivia','América do Sul',NULL,true,false,false,-16.3,-63.6),
('CHL','CL',152,'Chile','Chile','América do Sul',NULL,false,false,false,-33.0,-71.0),
('PER','PE',604,'Peru','Peru','América do Sul',NULL,false,false,false,-10.0,-75.0),
('COL','CO',170,'Colômbia','Colombia','América do Sul',NULL,false,false,false,4.0,-74.0),
('ECU','EC',218,'Equador','Ecuador','América do Sul',NULL,false,false,false,-1.8,-78.2),
('VEN','VE',862,'Venezuela','Venezuela','América do Sul',NULL,false,false,false,7.0,-66.0),
('USA','US',840,'Estados Unidos','United States','América do Norte',NULL,false,false,false,38.0,-98.0),
('CAN','CA',124,'Canadá','Canada','América do Norte',NULL,false,false,false,56.0,-100.0),
('MEX','MX',484,'México','Mexico','América do Norte',NULL,false,false,false,23.0,-102.0),
('DOM','DO',214,'República Dominicana','Dominican Republic','América Central e Caribe',NULL,false,false,false,19.0,-70.0),
('PAN','PA',591,'Panamá','Panama','América Central e Caribe',NULL,false,false,false,9.0,-80.0),
('CRI','CR',188,'Costa Rica','Costa Rica','América Central e Caribe',NULL,false,false,false,10.0,-84.0),
('GTM','GT',320,'Guatemala','Guatemala','América Central e Caribe',NULL,false,false,false,15.5,-90.3),
('JAM','JM',388,'Jamaica','Jamaica','América Central e Caribe',NULL,false,false,false,18.1,-77.3),
('PRI','PR',630,'Porto Rico','Puerto Rico','América Central e Caribe',NULL,false,false,false,18.2,-66.5),
('TTO','TT',780,'Trinidad e Tobago','Trinidad and Tobago','América Central e Caribe',NULL,false,false,false,10.7,-61.2),
('CUB','CU',192,'Cuba','Cuba','América Central e Caribe',NULL,false,false,false,21.5,-79.5),
('DEU','DE',276,'Alemanha','Germany','Europa','UE',false,true,false,51.0,10.0),
('BEL','BE',56,'Bélgica','Belgium','Europa','UE',false,true,false,50.8,4.5),
('NLD','NL',528,'Países Baixos','Netherlands','Europa','UE',false,true,false,52.3,5.0),
('FRA','FR',250,'França','France','Europa','UE',false,true,false,47.0,2.0),
('ESP','ES',724,'Espanha','Spain','Europa','UE',false,true,false,40.0,-4.0),
('ITA','IT',380,'Itália','Italy','Europa','UE',false,true,false,43.0,12.0),
('PRT','PT',620,'Portugal','Portugal','Europa','UE',false,true,false,39.5,-8.0),
('POL','PL',616,'Polônia','Poland','Europa','UE',false,true,false,52.0,19.0),
('IRL','IE',372,'Irlanda','Ireland','Europa','UE',false,true,false,53.3,-8.0),
('DNK','DK',208,'Dinamarca','Denmark','Europa','UE',false,true,false,56.0,10.0),
('SWE','SE',752,'Suécia','Sweden','Europa','UE',false,true,false,62.0,16.0),
('FIN','FI',246,'Finlândia','Finland','Europa','UE',false,true,false,63.0,26.0),
('AUT','AT',40,'Áustria','Austria','Europa','UE',false,true,false,47.5,14.5),
('CZE','CZ',203,'República Tcheca','Czechia','Europa','UE',false,true,false,49.8,15.5),
('GRC','GR',300,'Grécia','Greece','Europa','UE',false,true,false,39.0,22.0),
('ROU','RO',642,'Romênia','Romania','Europa','UE',false,true,false,46.0,25.0),
('HUN','HU',348,'Hungria','Hungary','Europa','UE',false,true,false,47.0,19.5),
('SVK','SK',703,'Eslováquia','Slovakia','Europa','UE',false,true,false,48.7,19.7),
('SVN','SI',705,'Eslovênia','Slovenia','Europa','UE',false,true,false,46.1,14.8),
('HRV','HR',191,'Croácia','Croatia','Europa','UE',false,true,false,45.1,15.2),
('BGR','BG',100,'Bulgária','Bulgaria','Europa','UE',false,true,false,42.7,25.5),
('LTU','LT',440,'Lituânia','Lithuania','Europa','UE',false,true,false,55.2,23.9),
('LVA','LV',428,'Letônia','Latvia','Europa','UE',false,true,false,56.9,24.6),
('EST','EE',233,'Estônia','Estonia','Europa','UE',false,true,false,58.6,25.0),
('GBR','GB',826,'Reino Unido','United Kingdom','Europa',NULL,false,false,false,53.0,-2.0),
('NOR','NO',578,'Noruega','Norway','Europa',NULL,false,false,false,61.0,8.5),
('CHE','CH',756,'Suíça','Switzerland','Europa',NULL,false,false,false,46.8,8.2),
('UKR','UA',804,'Ucrânia','Ukraine','Europa',NULL,false,false,false,49.0,32.0),
('BLR','BY',112,'Belarus','Belarus','Europa',NULL,false,false,false,53.7,28.0),
('RUS','RU',643,'Rússia','Russian Federation','Europa',NULL,false,false,false,60.0,90.0),
('TUR','TR',792,'Turquia','Türkiye','Oriente Médio',NULL,false,false,false,39.0,35.0),
('SAU','SA',682,'Arábia Saudita','Saudi Arabia','Oriente Médio',NULL,false,false,false,24.0,45.0),
('ARE','AE',784,'Emirados Árabes Unidos','United Arab Emirates','Oriente Médio',NULL,false,false,false,24.0,54.0),
('KWT','KW',414,'Kuwait','Kuwait','Oriente Médio',NULL,false,false,false,29.3,47.5),
('QAT','QA',634,'Catar','Qatar','Oriente Médio',NULL,false,false,false,25.3,51.2),
('OMN','OM',512,'Omã','Oman','Oriente Médio',NULL,false,false,false,21.5,56.0),
('JOR','JO',400,'Jordânia','Jordan','Oriente Médio',NULL,false,false,false,31.0,36.0),
('LBN','LB',422,'Líbano','Lebanon','Oriente Médio',NULL,false,false,false,33.9,35.9),
('ISR','IL',376,'Israel','Israel','Oriente Médio',NULL,false,false,false,31.0,35.0),
('IRQ','IQ',368,'Iraque','Iraq','Oriente Médio',NULL,false,false,false,33.0,44.0),
('IRN','IR',364,'Irã','Iran','Oriente Médio',NULL,false,false,false,32.0,53.0),
('EGY','EG',818,'Egito','Egypt','África',NULL,false,false,false,26.8,30.8),
('MAR','MA',504,'Marrocos','Morocco','África',NULL,false,false,false,32.0,-7.0),
('DZA','DZ',12,'Argélia','Algeria','África',NULL,false,false,false,28.0,3.0),
('TUN','TN',788,'Tunísia','Tunisia','África',NULL,false,false,false,34.0,9.0),
('ZAF','ZA',710,'África do Sul','South Africa','África',NULL,false,false,false,-29.0,25.0),
('NGA','NG',566,'Nigéria','Nigeria','África',NULL,false,false,false,9.1,8.7),
('GHA','GH',288,'Gana','Ghana','África',NULL,false,false,false,7.9,-1.0),
('CIV','CI',384,'Costa do Marfim','Côte d''Ivoire','África',NULL,false,false,false,7.5,-5.5),
('SEN','SN',686,'Senegal','Senegal','África',NULL,false,false,false,14.5,-14.5),
('GAB','GA',266,'Gabão','Gabon','África',NULL,false,false,false,-0.8,11.6),
('CMR','CM',120,'Camarões','Cameroon','África',NULL,false,false,false,7.4,12.4),
('AGO','AO',24,'Angola','Angola','África',NULL,false,false,false,-11.2,17.9),
('CHN','CN',156,'China','China','Ásia',NULL,false,false,false,33.0,104.0),
('HKG','HK',344,'Hong Kong','Hong Kong','Ásia',NULL,false,false,false,22.3,114.2),
('TWN','TW',158,'Taiwan','Taiwan','Ásia',NULL,false,false,false,23.7,121.0),
('JPN','JP',392,'Japão','Japan','Ásia',NULL,false,false,false,36.0,138.0),
('KOR','KR',410,'Coreia do Sul','Republic of Korea','Ásia',NULL,false,false,false,36.0,128.0),
('IND','IN',356,'Índia','India','Ásia',NULL,false,false,false,22.0,79.0),
('PAK','PK',586,'Paquistão','Pakistan','Ásia',NULL,false,false,false,30.0,70.0),
('BGD','BD',50,'Bangladesh','Bangladesh','Ásia',NULL,false,false,false,23.7,90.4),
('LKA','LK',144,'Sri Lanka','Sri Lanka','Ásia',NULL,false,false,false,7.9,80.8),
('VNM','VN',704,'Vietnã','Viet Nam','Ásia',NULL,false,false,false,16.0,106.0),
('THA','TH',764,'Tailândia','Thailand','Ásia',NULL,false,false,false,15.0,101.0),
('MYS','MY',458,'Malásia','Malaysia','Ásia',NULL,false,false,false,4.0,102.0),
('IDN','ID',360,'Indonésia','Indonesia','Ásia',NULL,false,false,false,-1.0,113.0),
('PHL','PH',608,'Filipinas','Philippines','Ásia',NULL,false,false,false,12.9,121.8),
('SGP','SG',702,'Singapura','Singapore','Ásia',NULL,false,false,false,1.35,103.8),
('AUS','AU',36,'Austrália','Australia','Oceania',NULL,false,false,false,-25.0,134.0),
('NZL','NZ',554,'Nova Zelândia','New Zealand','Oceania',NULL,false,false,false,-41.0,174.0);

INSERT INTO dw.dim_uf (uf, name_pt, region) VALUES
('AC','Acre','Norte'),('AL','Alagoas','Nordeste'),('AP','Amapá','Norte'),('AM','Amazonas','Norte'),('BA','Bahia','Nordeste'),
('CE','Ceará','Nordeste'),('DF','Distrito Federal','Centro-Oeste'),('ES','Espírito Santo','Sudeste'),('GO','Goiás','Centro-Oeste'),
('MA','Maranhão','Nordeste'),('MT','Mato Grosso','Centro-Oeste'),('MS','Mato Grosso do Sul','Centro-Oeste'),('MG','Minas Gerais','Sudeste'),
('PA','Pará','Norte'),('PB','Paraíba','Nordeste'),('PR','Paraná','Sul'),('PE','Pernambuco','Nordeste'),('PI','Piauí','Nordeste'),
('RJ','Rio de Janeiro','Sudeste'),('RN','Rio Grande do Norte','Nordeste'),('RS','Rio Grande do Sul','Sul'),('RO','Rondônia','Norte'),
('RR','Roraima','Norte'),('SC','Santa Catarina','Sul'),('SP','São Paulo','Sudeste'),('SE','Sergipe','Nordeste'),('TO','Tocantins','Norte'),
('--','Não declarada','—'),('ND','Não declarada (Comex)','—'),('EX','Exterior','—'),('ZN','Zona não declarada','—'),('RE','Reexportação','—'),('MN','Mercadoria nacionalizada','—'),('CB','Consumo de bordo','—');

-- Densidades: fatores aproximados, usados SÓ quando a unidade estatística não é m³.
INSERT INTO dw.dim_product (product_code, family, name_pt, name_en, density_kg_m3, density_note, is_celplac_core) VALUES
('ROUNDWOOD_PINE','roundwood','Madeira em tora — pinus','Pine logs',850,'tora verde; validar',false),
('ROUNDWOOD_EUCALYPTUS','roundwood','Madeira em tora — eucalipto','Eucalyptus logs',1000,'tora verde; validar',false),
('SAWN_PINE','sawnwood','Madeira serrada — pinus','Pine sawnwood',500,'seca ao ar; validar',false),
('SAWN_TROPICAL','sawnwood','Madeira serrada — tropical','Tropical sawnwood',750,'média de espécies; validar',false),
('VENEER_CONIFER','veneer','Lâminas — coníferas','Coniferous veneer',550,'validar',true),
('VENEER_TROPICAL','veneer','Lâminas — tropicais','Tropical veneer',650,'validar',true),
('VENEER_OTHER','veneer','Lâminas — outras (ex.: eucalipto)','Other veneer',620,'validar',true),
('PARTICLEBOARD','panels','Painel de partículas (aglomerado)','Particleboard',650,'validar',false),
('MDF','panels','MDF / HDF','MDF / HDF',720,'validar',false),
('PLYWOOD_TROPICAL','plywood','Compensado — face tropical','Tropical plywood',600,'validar',true),
('PLYWOOD_HARDWOOD','plywood','Compensado — face não conífera','Hardwood plywood',600,'validar',true),
('PLYWOOD_CONIFER','plywood','Compensado — faces coníferas (pinus)','Softwood plywood',520,'validar',true),
('PLYWOOD_BAMBOO','plywood','Compensado de bambu','Bamboo plywood',700,'validar',false),
('LVL_TROPICAL','lvl','LVL — face tropical','Tropical LVL',620,'validar',true),
('LVL_HARDWOOD','lvl','LVL — face não conífera','Hardwood LVL',600,'validar',true),
('LVL_CONIFER','lvl','LVL — faces coníferas','Softwood LVL',520,'validar',true);

INSERT INTO dw.map_hs6_product (hs6, product_code, description_pt, note) VALUES
('440321','ROUNDWOOD_PINE','Madeira em bruto — pinus (Pinus spp.), seção transversal ≥ 15 cm',NULL),
('440322','ROUNDWOOD_PINE','Madeira em bruto — pinus (Pinus spp.), outras',NULL),
('440398','ROUNDWOOD_EUCALYPTUS','Madeira em bruto — eucalipto (Eucalyptus spp.)',NULL),
('440711','SAWN_PINE','Madeira serrada — pinus (Pinus spp.)',NULL),
('440729','SAWN_TROPICAL','Madeira serrada — tropicais, outras',NULL),
('440810','VENEER_CONIFER','Folhas para folheados / lâminas — coníferas',NULL),
('440831','VENEER_TROPICAL','Folhas para folheados — dark red meranti, light red meranti e meranti bakau',NULL),
('440839','VENEER_TROPICAL','Folhas para folheados — tropicais, outras',NULL),
('440890','VENEER_OTHER','Folhas para folheados — outras',NULL),
('441011','PARTICLEBOARD','Painéis de partículas (aglomerado)',NULL),
('441112','MDF','MDF — espessura ≤ 5 mm',NULL),
('441113','MDF','MDF — espessura > 5 mm e ≤ 9 mm',NULL),
('441114','MDF','MDF — espessura > 9 mm',NULL),
('441210','PLYWOOD_BAMBOO','Compensado de bambu',NULL),
('441231','PLYWOOD_TROPICAL','Compensado — ao menos uma face de madeira tropical',NULL),
('441233','PLYWOOD_HARDWOOD','Compensado — ao menos uma face de não conífera das espécies listadas',NULL),
('441234','PLYWOOD_HARDWOOD','Compensado — ao menos uma face de não conífera, outras (ex.: eucalipto)',NULL),
('441239','PLYWOOD_CONIFER','Compensado — ambas as faces de coníferas',NULL),
('441241','LVL_TROPICAL','LVL — ao menos uma face de madeira tropical','Desdobramento introduzido na HS2022'),
('441242','LVL_HARDWOOD','LVL — outro, ao menos uma face de não conífera','Desdobramento introduzido na HS2022'),
('441249','LVL_CONIFER','LVL — ambas as faces de coníferas','Desdobramento introduzido na HS2022');

INSERT INTO dw.dim_port (port_code, name, country_iso3, unlocode, kind, lat, lon) VALUES
('BRPNG','Paranaguá','BRA','BRPNG','seaport',-25.50,-48.52),
('BRITJ','Itajaí','BRA','BRITJ','seaport',-26.90,-48.66),
('BRIOA','Itapoá','BRA','BRIOA','seaport',-26.12,-48.61),
('BRSFS','São Francisco do Sul','BRA','BRSFS','seaport',-26.24,-48.64),
('BRRIG','Rio Grande','BRA','BRRIG','seaport',-32.03,-52.10),
('BRSSZ','Santos','BRA','BRSSZ','seaport',-23.95,-46.33),
('BRUGU','Uruguaiana (fronteira)','BRA',NULL,'border',-29.75,-57.09),
('BRFOZ','Foz do Iguaçu (fronteira)','BRA',NULL,'border',-25.55,-54.58),
('USHOU','Houston','USA','USHOU','seaport',29.73,-95.27),
('USSAV','Savannah','USA','USSAV','seaport',32.08,-81.09),
('NLRTM','Roterdã','NLD','NLRTM','seaport',51.95,4.14),
('BEANR','Antuérpia','BEL','BEANR','seaport',51.26,4.40),
('DEHAM','Hamburgo','DEU','DEHAM','seaport',53.54,9.97),
('GBFXT','Felixstowe','GBR','GBFXT','seaport',51.95,1.33),
('MXVER','Veracruz','MEX','MXVER','seaport',19.20,-96.13),
('MXZLO','Manzanillo','MEX','MXZLO','seaport',19.05,-104.31),
('CNSHA','Xangai','CHN','CNSHA','seaport',31.23,121.47),
('SAJED','Jeddah','SAU','SAJED','seaport',21.48,39.17);

INSERT INTO dw.dim_indicator (indicator_code, name_pt, unit, frequency, kind, polarity, category, source_id, source_ref, formula, pulse_key, description) VALUES
('WOOD_PRICE_INDEX','Wood Price Index','pts','M','data',1,'price','itto',NULL,NULL,'WOOD','Índice de preços de madeira (importação manual)'),
('PLYWOOD_FOB_BR','Compensado BR — preço médio FOB','US$/m³','M','indicator',1,'price','gwmi_calc',NULL,'sum(value_usd_fob)/sum(qty_m3) — BRA, flow X, family plywood','PLYWOOD','Derivado de dw.fact_trade'),
('VENEER_PRICE_INDEX','Veneer Price Index','pts','M','data',1,'price','itto',NULL,NULL,'VENEER',NULL),
('CONSTRUCTION_COMPOSITE','Construção — índice composto','pts','M','indicator',1,'construction','gwmi_calc',NULL,'média ponderada de índices de construção (EUA, UE, China, México)','CONSTRUCTION',NULL),
('BR_TRAILERS_REG','Implementos rodoviários — emplacamentos','un./mês','M','data',1,'trucking','anfir',NULL,NULL,'TRUCKING',NULL),
('FREIGHT_CONTAINER_INDEX','Frete contêiner — índice','US$/FEU','W','data',-1,'freight','drewry',NULL,NULL,'SHIPPING',NULL),
('FX_USD_BRL','Dólar comercial PTAX (venda)','R$','D','data',1,'fx','bcb_ptax','USD',NULL,'USD/BRL',NULL),
('FX_EUR_BRL','Euro PTAX (venda)','R$','D','data',1,'fx','bcb_ptax','EUR',NULL,NULL,NULL),
('FX_GBP_BRL','Libra PTAX (venda)','R$','D','data',1,'fx','bcb_ptax','GBP',NULL,NULL,NULL),
('FX_CNY_BRL','Yuan (venda)','R$','D','data',1,'fx','bcb_ptax','CNY',NULL,NULL,'Confirmar disponibilidade do CNY no serviço PTAX; alternativa: fonte a definir'),
('FX_MXN_BRL','Peso mexicano (venda)','R$','D','data',1,'fx','bcb_ptax','MXN',NULL,NULL,'Confirmar disponibilidade do MXN no serviço PTAX; alternativa: fonte a definir'),
('CN_WOOD_IMPORTS','China — importações de madeira (cap. 44)','US$ bi','M','data',1,'trade','comtrade','44',NULL,'CHINA',NULL),
('US_HOUSING_STARTS','EUA — housing starts','mil/ano (SAAR)','M','data',1,'construction','fred','HOUST',NULL,'USA',NULL),
('EU_PLYWOOD_IMPORTS','UE — importações de compensados','mil m³','M','data',1,'trade','eurostat','4412',NULL,'EUROPE',NULL),
('EXP_BR_VALUE','Exportações BR (cap. 44 selecionado) — valor','US$','M','indicator',1,'trade','gwmi_calc',NULL,'sum(value_usd_fob) — BRA, flow X, por parceiro',NULL,'Base dos sinais por mercado'),
('EXP_BR_M3','Exportações BR — volume','m³','M','indicator',1,'trade','gwmi_calc',NULL,'sum(qty_m3) — BRA, flow X, por parceiro',NULL,NULL),
('IMP_TOTAL_WOOD','Importações totais do mercado (SH 4412)','US$','M','data',1,'trade','comtrade','4412',NULL,NULL,'Importações do destino, todas as origens'),
('FREIGHT_BR_USEC','Frete BR → EUA costa leste','US$/FEU','W','data',-1,'freight','drewry',NULL,NULL,NULL,NULL),
('FREIGHT_BR_NEUR','Frete BR → Norte da Europa','US$/FEU','W','data',-1,'freight','drewry',NULL,NULL,NULL,NULL),
('FREIGHT_BR_ASIA','Frete BR → Ásia','US$/FEU','W','data',-1,'freight','fbx',NULL,NULL,NULL,NULL),
('BRENT','Petróleo Brent','US$/bbl','D','data',-1,'energy','eia','RBRTE',NULL,NULL,NULL),
('PRICE_LOG_PINUS','Tora de pinus (serraria)','R$/m³','M','data',-1,'price','iba',NULL,NULL,NULL,'Custo de matéria-prima'),
('PRICE_RESIN_PHENOLIC','Resina fenólica','R$/kg','M','data',-1,'price','celplac_erp',NULL,NULL,NULL,'Cotação de fornecedores (Fase 5)'),
('MACRO_POLICY_RATE','Juros básicos','% a.a.','M','data',-1,'macro','imf',NULL,NULL,NULL,NULL),
('MACRO_CPI_YOY','Inflação','% a/a','M','data',-1,'macro','imf',NULL,NULL,NULL,NULL),
('MACRO_GDP_YOY','PIB','% a/a','Q','data',1,'macro','imf',NULL,NULL,NULL,NULL),
('MACRO_IP_YOY','Produção industrial','% a/a','M','data',1,'macro','imf',NULL,NULL,NULL,NULL),
('MACRO_UNEMP','Desemprego','%','M','data',-1,'macro','imf',NULL,NULL,NULL,NULL),
('MACRO_CONSTRUCTION_YOY','Construção','% a/a','M','data',1,'macro','imf',NULL,NULL,NULL,NULL),
('MACRO_CONFIDENCE','Confiança','pts','M','data',1,'macro','worldbank',NULL,NULL,NULL,NULL),
('BR_IP_WOOD','BR — produção industrial: produtos de madeira','índice','M','data',1,'production','ibge_sidra','8888',NULL,NULL,'PIM-PF — confirmar tabela/variável'),
('BR_SILV_PINUS_M3','BR — silvicultura: tora de pinus','m³','A','data',1,'production','ibge_sidra','291',NULL,NULL,'PEVS — confirmar tabela/classificação'),
('BR_SILV_EUCA_M3','BR — silvicultura: tora de eucalipto','m³','A','data',1,'production','ibge_sidra','291',NULL,NULL,'PEVS — confirmar tabela/classificação'),
('FAO_PLYWOOD_PROD','Produção de compensado (FAO)','m³','A','data',1,'production','fao','Plywood|Production',NULL,NULL,NULL),
('FAO_PLYWOOD_EXP','Exportação de compensado (FAO)','m³','A','data',1,'trade','fao','Plywood|Export Quantity',NULL,NULL,NULL),
('FAO_VENEER_PROD','Produção de lâminas (FAO)','m³','A','data',1,'production','fao','Veneer sheets|Production',NULL,NULL,NULL),
('FAO_PANELS_PROD','Produção de painéis de madeira (FAO)','m³','A','data',1,'production','fao','Wood-based panels|Production',NULL,NULL,NULL);

INSERT INTO meta.setting (key, value, description) VALUES
('cycle', '{"momentum_threshold":0.01,"indicators":["PLYWOOD_FOB_BR","VENEER_PRICE_INDEX","CONSTRUCTION_COMPOSITE","BR_TRAILERS_REG","FREIGHT_CONTAINER_INDEX","US_HOUSING_STARTS","EU_PLYWOOD_IMPORTS","WOOD_PRICE_INDEX"]}',
 'Market Cycle: nível vs média 5a × momentum 6m; limiar de momentum e indicadores posicionados'),
('api', '{"allow_simulated":true}', 'Se false, a API nunca serve dado simulado (responde DADO INDISPONÍVEL)');

INSERT INTO intel.signal_rule (rule_id, version, name, tone, markets, conditions) VALUES
('market_pressure', 1, 'SINAL DE PRESSÃO DE MERCADO', 'neg', '{USA,MEX,EUU,CHN,ARG,SAU}',
 '[{"label":"Exportações BR ↓","indicator":"EXP_BR_VALUE","geo":"{market}","test":"down","window":3,"threshold":0.02},
   {"label":"Importações do destino ↓","indicator":"IMP_TOTAL_WOOD","geo":"{market}","test":"down","window":3,"threshold":0.02},
   {"label":"Preço ↓","indicator":"PLYWOOD_FOB_BR","geo":"BRA","test":"down","window":3,"threshold":0.01},
   {"label":"Frete ↑","indicator":"FREIGHT_CONTAINER_INDEX","geo":"WLD","test":"up","window":3,"threshold":0.02}]'),
('demand_expansion', 1, 'SINAL DE EXPANSÃO DA DEMANDA', 'pos', '{USA,MEX,EUU,CHN,ARG,SAU}',
 '[{"label":"Construção ↑","indicator":"MACRO_CONSTRUCTION_YOY","geo":"{market}","test":"positive"},
   {"label":"Produção industrial ↑","indicator":"MACRO_IP_YOY","geo":"{market}","test":"positive"},
   {"label":"Importações ↑","indicator":"IMP_TOTAL_WOOD","geo":"{market}","test":"up","window":3,"threshold":0.02},
   {"label":"Frete estável","indicator":"FREIGHT_CONTAINER_INDEX","geo":"WLD","test":"stable","window":3,"threshold":0.05}]'),
('cost_pressure', 1, 'SINAL DE PRESSÃO DE CUSTO', 'warn', '{BRA}',
 '[{"label":"Tora ↑","indicator":"PRICE_LOG_PINUS","geo":"BRA","test":"up","window":3,"threshold":0.02},
   {"label":"Resina ↑","indicator":"PRICE_RESIN_PHENOLIC","geo":"BRA","test":"up","window":3,"threshold":0.02},
   {"label":"Petróleo ↑","indicator":"BRENT","geo":"WLD","test":"up","window":3,"threshold":0.03},
   {"label":"Câmbio ↓ (real mais forte)","indicator":"FX_USD_BRL","geo":"BRA","test":"down","window":3,"threshold":0.01}]');

INSERT INTO intel.index_config (name, components, is_default, note) VALUES
('CELPLAC GWMI — pesos iguais (v1)',
 '[{"indicator":"CONSTRUCTION_COMPOSITE","geo":"WLD","weight":10,"invert":false},
   {"indicator":"PLYWOOD_FOB_BR","geo":"BRA","weight":10,"invert":false},
   {"indicator":"VENEER_PRICE_INDEX","geo":"WLD","weight":10,"invert":false},
   {"indicator":"EXP_BR_VALUE","geo":"WLD","weight":10,"invert":false},
   {"indicator":"EU_PLYWOOD_IMPORTS","geo":"EUU","weight":10,"invert":false},
   {"indicator":"FREIGHT_CONTAINER_INDEX","geo":"WLD","weight":10,"invert":true},
   {"indicator":"FX_USD_BRL","geo":"BRA","weight":10,"invert":false},
   {"indicator":"WOOD_PRICE_INDEX","geo":"WLD","weight":10,"invert":false},
   {"indicator":"CN_WOOD_IMPORTS","geo":"CHN","weight":10,"invert":false},
   {"indicator":"BR_TRAILERS_REG","geo":"BRA","weight":10,"invert":false}]',
 true, 'Pesos iguais por construção — não definitivos. Estudo estatístico de pesos previsto na Fase 4.');
